djenealog/urls.py
from django.urls import path
from django.views.generic import ListView, TemplateView

from . import models, views

app_name = "djenealog"
urlpatterns = [
    path("", TemplateView.as_view(template_name="djenealog/home.html"), name="home"),
    path("graph", views.gv, name="graph"),
    path("img.svg", views.img_svg, name="img-svg"),
    path("annivs", views.annivs, name="annivs"),
    path("stats", views.stats, name="stats"),
    path("individus", views.IndividusView.as_view(), name="individus"),
    path("individu/create", views.IndividuCreateView.as_view(), name="add-individu"),
    path("individu/<int:pk>", views.IndividuView.as_view(), name="individu"),
    path(
        "individu/<int:pk>/delete",
        views.ModelDeleteView.as_view(model=models.Individu),
        name="del-individu",
    ),
    path("couples", views.CouplesView.as_view(), name="couples"),
    path("couple/create", views.CoupleCreateView.as_view(), name="add-couple"),
    path("couple/<int:pk>", views.CoupleView.as_view(), name="couple"),
    path(
        "couple/<int:pk>/delete",
        views.ModelDeleteView.as_view(model=models.Couple),
        name="del-couple",
    ),
    path(
        "pacs/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Pacs),
        name="pacs",
    ),
    path(
        "pacs/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Pacs),
        name="add-pacs",
    ),
    path(
        "pacs/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Pacs),
        name="del-pacs",
    ),
    path(
        "mariage/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Mariage),
        name="mariage",
    ),
    path(
        "mariage/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Mariage),
        name="add-mariage",
    ),
    path(
        "mariage/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Mariage),
        name="del-mariage",
    ),
    path(
        "divorce/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Divorce),
        name="divorce",
    ),
    path(
        "divorce/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Divorce),
        name="add-divorce",
    ),
    path(
        "divorce/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Divorce),
        name="del-divorce",
    ),
    path(
        "naissance/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Naissance),
        name="naissance",
    ),
    path(
        "naissance/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Naissance),
        name="add-naissance",
    ),
    path(
        "naissance/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Naissance),
        name="del-naissance",
    ),
    path(
        "deces/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Deces),
        name="deces",
    ),
    path(
        "deces/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Deces),
        name="add-deces",
    ),
    path(
        "deces/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Deces),
        name="del-deces",
    ),
    path("lieux", ListView.as_view(model=models.Lieu), name="lieux"),
]

testproject/urls.py
from django.contrib.gis import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("select2/", include("django_select2.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("djenealog.urls")),
]

testproject/templates/base.html
{% extends 'ndh.html' %}
{% load ndh %}

{% block pagetitle %}Djenealog{% endblock %}
{% block sitetitle %}Djenealog{% endblock %}

{% block navbarleft %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" id="djenealogDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
    Djenealog
  </a>
  <ul class="dropdown-menu" aria-labelledby="djenealogDropdown">
    <li><a class="dropdown-item" href="{% url 'djenealog:graph' %}">Graphe</a></li>
    <li><a class="dropdown-item" href="{% url 'djenealog:stats' %}">Stats</a></li>
    <li><a class="dropdown-item" href="{% url 'djenealog:annivs' %}">Anniversaires</a></li>
      {% if request.user.is_superuser %}
      <li><a class="dropdown-item" href="{% url 'djenealog:individus' %}">Individus</a></li>
      <li><a class="dropdown-item" href="{% url 'djenealog:couples' %}">Couples</a></li>
      <li><a class="dropdown-item" href="{% url 'djenealog:add-individu' %}">Add Individu</a></li>
      <li><a class="dropdown-item" href="{% url 'djenealog:add-couple' %}">Add Couple</a></li>
      <li><a class="dropdown-item" href="{% url 'djenealog:lieux' %}">Lieux</a></li>
      {% endif %}
  </ul>
</li>
{% endblock %}