djenealog/urls.py
from django.urls import path
from django.views.generic import ListView, TemplateView

from . import models, views

app_name = "djenealog"
urlpatterns = [
    path("", TemplateView.as_view(template_name="djenealog/home.html"), name="home"),
    path("graph", views.gv, name="graph"),
    path("img.svg", views.img_svg, name="img-svg"),
    path("annivs", views.annivs, name="annivs"),
    path("stats", views.stats, name="stats"),
    path("individus", views.IndividusView.as_view(), name="individus"),
    path("individu/create", views.IndividuCreateView.as_view(), name="add-individu"),
    path("individu/<int:pk>", views.IndividuView.as_view(), name="individu"),
    path(
        "individu/<int:pk>/delete",
        views.ModelDeleteView.as_view(model=models.Individu),
        name="del-individu",
    ),
    path("couples", views.CouplesView.as_view(), name="couples"),
    path("couple/create", views.CoupleCreateView.as_view(), name="add-couple"),
    path("couple/<int:pk>", views.CoupleView.as_view(), name="couple"),
    path(
        "couple/<int:pk>/delete",
        views.ModelDeleteView.as_view(model=models.Couple),
        name="del-couple",
    ),
    path(
        "pacs/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Pacs),
        name="pacs",
    ),
    path(
        "pacs/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Pacs),
        name="add-pacs",
    ),
    path(
        "pacs/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Pacs),
        name="del-pacs",
    ),
    path(
        "mariage/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Mariage),
        name="mariage",
    ),
    path(
        "mariage/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Mariage),
        name="add-mariage",
    ),
    path(
        "mariage/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Mariage),
        name="del-mariage",
    ),
    path(
        "divorce/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Divorce),
        name="divorce",
    ),
    path(
        "divorce/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Divorce),
        name="add-divorce",
    ),
    path(
        "divorce/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Divorce),
        name="del-divorce",
    ),
    path(
        "naissance/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Naissance),
        name="naissance",
    ),
    path(
        "naissance/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Naissance),
        name="add-naissance",
    ),
    path(
        "naissance/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Naissance),
        name="del-naissance",
    ),
    path(
        "deces/<int:pk>",
        views.EvenementUpdateView.as_view(model=models.Deces),
        name="deces",
    ),
    path(
        "deces/<int:pk>/create",
        views.EvenementCreateView.as_view(model=models.Deces),
        name="add-deces",
    ),
    path(
        "deces/<int:pk>/delete",
        views.EvenementDeleteView.as_view(model=models.Deces),
        name="del-deces",
    ),
    path("lieux", ListView.as_view(model=models.Lieu), name="lieux"),
]

testproject/urls.py
from django.contrib.gis import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("select2/", include("django_select2.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path("", include("djenealog.urls")),
]

djenealog/forms.py
from typing import ClassVar

from django.forms import ModelForm

from django_select2.forms import Select2Widget

from . import models


class IndividuForm(ModelForm):
    class Meta:
        model = models.Individu
        fields = (
            "prenom",
            "usage",
            "nom",
            "epouse",
            "masculin",
            "parents",
            "commentaires",
        )
        widgets: ClassVar = {
            "parents": Select2Widget,
        }


class CoupleForm(ModelForm):
    class Meta:
        model = models.Couple
        fields = ("mari", "femme", "debut", "fin", "commentaires")
        widgets: ClassVar = {
            "mari": Select2Widget,
            "femme": Select2Widget,
        }

djenealog/views.py
from calendar import LocaleHTMLCalendar
from datetime import date
from subprocess import check_output

from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.http.response import HttpResponse
from django.shortcuts import render
from django.template.loader import get_template
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, DeleteView, UpdateView

from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from ndh.mixins import SuperUserRequiredMixin

from . import filters, forms, models, tables


# @login_required
def gv(request):
    fmt = request.GET.get("fmt", "html")
    condensed = "condensed" in request.GET
    individus = models.Individu.objects.all()
    couples = models.Couple.objects.all()
    if "famille" in request.GET:
        nom = request.GET["famille"].lower()
        individus = individus.filter(
            Q(nom__icontains=nom)
            | Q(femme__mari__nom__icontains=nom)
            | Q(mari__femme__nom__icontains=nom)
            | Q(parents__mari__nom__icontains=nom)
            | Q(parents__femme__nom__icontains=nom),
        )
        couples = couples.filter(
            Q(mari__nom__icontains=nom) | Q(femme__nom__icontains=nom),
        )
    if "individu" in request.GET:
        individus = set(
            individus.get(pk=int(request.GET["individu"])).family(
                extended="extended" in request.GET,
                upper="upper" in request.GET,
                lower="lower" in request.GET,
            ),
        )
        couples = couples.filter(Q(mari__in=individus) | Q(femme__in=individus))
        for couple in couples:
            if couple.mari:
                individus.add(couple.mari)
            if couple.femme:
                individus.add(couple.femme)
            individus |= set(couple.enfants.all())
    return render(
        request,
        f"djenealog/graph.{fmt}",
        {
            "years": range(
                models.Naissance.objects.exclude(y=None).order_by("y").first().y,
                date.today().year + 1,
            ),
            "individus": individus,
            "couples": couples,
            "condensed": condensed,
        },
    )


# @login_required
@cache_page(60 * 60 * 24)
def img_svg(request):
    individus = models.Individu.objects.all()
    couples = models.Couple.objects.all()
    gv = get_template("djenealog/graph.gv").render(
        {
            "years": range(
                models.Naissance.objects.exclude(y=None).order_by("y").first().y,
                date.today().year + 1,
            ),
            "individus": individus,
            "couples": couples,
        },
    )
    svg = check_output(["dot", "-Tsvg"], input=gv, text=True)
    return HttpResponse(svg, content_type="image/svg+xml")


def stats(request):
    prenom, usage, nom, epouse = (
        {
            row[field]: row["total"]
            for row in models.Individu.objects.all()
            .values(field)
            .annotate(total=Count(field))
            if row[field] != ""
        }
        for field in ("prenom", "usage", "nom", "epouse")
    )

    # merge eg 'Marie-Christine' & 'Marie Christine'
    drop = set()
    for p in prenom.keys():
        if "-" in p and p.replace("-", " ") in prenom.keys():
            prenom[p.replace("-", " ")] += prenom[p]
            drop.add(p)
    prenom = {k: v for k, v in prenom.items() if k not in drop}

    noms, prenoms = set(list(nom.keys()) + list(epouse.keys())), set(
        list(prenom.keys()) + list(usage.keys()),
    )
    noms = [
        (nom.get(n, 0) + epouse.get(n, 0), nom.get(n, 0), epouse.get(n, 0), n)
        for n in noms
        if n != ""
    ]
    prenoms = [
        (prenom.get(n, 0) + usage.get(n, 0), prenom.get(n, 0), usage.get(n, 0), n)
        for n in prenoms
        if n != ""
    ]

    centenaires = models.Individu.objects.filter(
        deces__isnull=True,
        naissance__y__lt=date.today().year - 100,
    )
    maris_pas_masculins = models.Couple.objects.exclude(mari__masculin=True).exclude(
        mari__isnull=True,
    )
    femmes_pas_feminines = models.Couple.objects.exclude(femme__masculin=False).exclude(
        femme__isnull=True,
    )
    divorces_sans_mariages = models.Couple.objects.filter(
        divorce__isnull=False,
        mariage__isnull=True,
    )
    assexues = models.Individu.objects.filter(masculin=None)

    return render(
        request,
        "djenealog/stats.html",
        {
            "individus": models.Individu.objects.count(),
            "couples": models.Couple.objects.count(),
            "naissances": models.Naissance.objects.count(),
            "deces": models.Deces.objects.count(),
            "mariages": models.Mariage.objects.count(),
            "divorces": models.Divorce.objects.count(),
            "pacs": models.Pacs.objects.count(),
            "noms": sorted(noms, reverse=True),
            "prenoms": sorted(prenoms, reverse=True),
            "hommes": models.Individu.objects.filter(masculin=True).count(),
            "femmes": models.Individu.objects.filter(masculin=False).count(),
            "centenaires": centenaires.count(),
            "maris_pas_masculins": maris_pas_masculins.count(),
            "femmes_pas_feminines": femmes_pas_feminines.count(),
            "divorces_sans_mariages": divorces_sans_mariages.count(),
            "assexues": assexues.count(),
        },
    )


@login_required
def annivs(request):
    class AnnivCalendar(LocaleHTMLCalendar):
        cssclass_year = "year table"
        cssclass_month = "month table"

        def __init__(self, annivs, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.annivs = annivs

        def formatday(self, day, weekday):
            if day == 0:
                return '<td class="noday"> </td>'  # day outside month
            annivs = ",<br />".join(
                f"{anniv.symbol} {anniv.inst.get_link()} ({anniv.y})"
                for anniv in self.annivs[(self.current_month, day)]
            )
            return f'<td><span class="font-italic">{day}</span><br />{annivs}</td>'

        def formatmonth(self, theyear, themonth, withyear=True):
            self.current_month = themonth
            return super().formatmonth(theyear, themonth, withyear)

    annivs = {(m, d): [] for m in range(13) for d in range(32)}

    if "individu" in request.GET:
        individus = models.Individu.objects.get(pk=int(request.GET["individu"])).family(
            extended="extended" in request.GET,
            upper="upper" in request.GET,
            lower="lower" in request.GET,
        )
        couples = models.Couple.objects.filter(
            Q(mari__in=individus) | Q(femme__in=individus),
        )
        for couple in couples:
            if couple.mari:
                individus.add(couple.mari)
            if couple.femme:
                individus.add(couple.femme)
            individus |= set(couple.enfants.all())

        for anniv in models.Naissance.objects.filter(
            m__isnull=False,
            d__isnull=False,
            inst__in=individus,
        ).order_by("y"):
            annivs[(anniv.m, anniv.d)].append(anniv)
    else:
        for event in [models.Naissance, models.Mariage, models.Pacs]:
            for anniv in event.objects.filter(
                m__isnull=False,
                d__isnull=False,
            ).order_by("y"):
                annivs[(anniv.m, anniv.d)].append(anniv)

    anniv_cal = AnnivCalendar(annivs).formatyear(date.today().year, 1)
    return render(request, "djenealog/annivs.html", {"anniv_cal": anniv_cal})


class IndividusView(SuperUserRequiredMixin, SingleTableMixin, FilterView):
    model = models.Individu
    table_class = tables.IndividuTable
    filterset_class = filters.IndividuFilter


class CouplesView(SuperUserRequiredMixin, SingleTableMixin, FilterView):
    model = models.Couple
    table_class = tables.CoupleTable
    filterset_class = filters.CoupleFilter


class IndividuView(SuperUserRequiredMixin, UpdateView):
    model = models.Individu
    form_class = forms.IndividuForm


class CoupleView(SuperUserRequiredMixin, UpdateView):
    model = models.Couple
    form_class = forms.CoupleForm


class IndividuCreateView(SuperUserRequiredMixin, CreateView):
    model = models.Individu
    form_class = forms.IndividuForm


class CoupleCreateView(SuperUserRequiredMixin, CreateView):
    model = models.Couple
    form_class = forms.CoupleForm


class EvenementMixin(SuperUserRequiredMixin):
    fields = ("d", "m", "y", "lieu", "commentaires")
    template_name = "djenealog/evenement_form.html"

    def get_success_url(self):
        return self.object.inst.get_absolute_url()


class EvenementUpdateView(EvenementMixin, UpdateView):
    pass


class EvenementCreateView(EvenementMixin, CreateView):
    def form_valid(self, form):
        form.instance.inst_id = self.kwargs.get(self.pk_url_kwarg)
        return super().form_valid(form)


class ModelDeleteView(SuperUserRequiredMixin, DeleteView):
    template_name = "djenealog/confirm_delete.html"
    success_url = "/"


class EvenementDeleteView(ModelDeleteView):
    def get_success_url(self):
        return self.object.inst.get_absolute_url()

djenealog/templates/djenealog/annivs.html
{% extends 'base.html' %}

{% block style %}
<style>
.month td { width: 14.28%; }
th.month, th.year { text-align: center; }
</style>
{% endblock %}

{% block content %}
{{ anniv_cal|safe }}
{% endblock %}

djenealog/templates/djenealog/confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/delete.html' %}
{% endblock %}

djenealog/templates/djenealog/couple_filter.html
{% extends 'base.html' %}
{% load django_tables2 django_bootstrap5 %}

{% block content %}

<h1>Couples</h1>

<a href="{% url 'djenealog:add-couple' %}">Add</a>

{% if filter %}
<form action="" method="get" class="form form-inline">
  {% bootstrap_form filter.form layout='inline' %}
  {% bootstrap_button 'filter' %}
</form>
{% endif %}

{% render_table table %}

{% endblock %}

djenealog/templates/djenealog/couple_form.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/form.html' %}

{% if couple.pk %}

<dl class="row">
  {% if couple.mari %}
  <dt class="col-sm-3">Mari</dt>
  <dd class="col-sm-9">{{ couple.mari.get_link }}</dd>
  {% endif %}
  {% if couple.femme %}
  <dt class="col-sm-3">Femme</dt>
  <dd class="col-sm-9">{{ couple.femme.get_link }}</dd>
  {% endif %}
  {% if couple.enfants.exists %}
  <dt class="col-sm-3">Enfants</dt>
  <dd class="col-sm-9">{% for enfant in couple.enfants.all %}{{ enfant.get_link }}{% if not forloop.last %}, {% endif %}{% endfor %}</dd>
  {% endif %}

  <dt class="col-sm-3">PACS</dt>
  <dd class="col-sm-9">
  {% if couple.pacs %}
  {{ couple.pacs }}
  <a href="{% url 'djenealog:pacs' pk=couple.pacs.pk %}">edit</a>
  <a href="{% url 'djenealog:del-pacs' pk=couple.pacs.pk %}">delete</a>
  {% else %}
  <a href="{% url 'djenealog:add-pacs' pk=couple.pk %}">Ajouter un PACS</a>
  {% endif %}
  </dd>

  <dt class="col-sm-3">Mariage</dt>
  <dd class="col-sm-9">
  {% if couple.mariage %}
  {{ couple.mariage }}
  <a href="{% url 'djenealog:mariage' pk=couple.mariage.pk %}">edit</a>
  <a href="{% url 'djenealog:del-mariage' pk=couple.mariage.pk %}">delete</a>
  {% else %}
  <a href="{% url 'djenealog:add-mariage' pk=couple.pk %}">Ajouter un Mariage</a>
  {% endif %}
  </dd>

  <dt class="col-sm-3">Divorce</dt>
  <dd class="col-sm-9">
  {% if couple.divorce %}
  {{ couple.divorce }}
  <a href="{% url 'djenealog:divorce' pk=couple.divorce.pk %}">edit</a>
  <a href="{% url 'djenealog:del-divorce' pk=couple.divorce.pk %}">delete</a>
  {% else %}
  <a href="{% url 'djenealog:add-divorce' pk=couple.pk %}">Ajouter un Divorce</a>
  {% endif %}
  </dd>

  <dt class="col-sm-3">Supprimer</dt>
  <dd class="col-sm-9"><a href="{% url 'djenealog:del-couple' pk=couple.pk %}">delete</a></dd>
</dl>

{% endif %}

{% endblock %}

{% block style %}
{{ form.media.css }}
{% endblock %}

{% block scripts %}
{{ form.media.js }}
{% endblock %}

djenealog/templates/djenealog/evenement_form.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/form.html' %}
{{ object.inst.get_link }}
{% endblock %}

djenealog/templates/djenealog/form.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/form.html' %}
{% endblock %}

djenealog/templates/djenealog/graph.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="graph"></div>
{% endblock %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="{% static 'js/viz-lite.js' %}"></script>

<script type="txt/vnd.graphviz" id='graphe'>
{% include 'djenealog/graph.gv' %}
</script>
<script>$('#graph').html(Viz($('#graphe').html(), 'svg'));</script>
{% endblock %}

djenealog/templates/djenealog/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Hello</h1>
{% endblock %}

djenealog/templates/djenealog/individu_filter.html
{% extends 'base.html' %}
{% load django_tables2 django_bootstrap5 %}

{% block content %}

<h1>Individus</h1>

<a href="{% url 'djenealog:add-individu' %}">Add</a>

{% if filter %}
<form action="" method="get" class="form form-inline">
  {% bootstrap_form filter.form layout='inline' %}
  {% bootstrap_button 'filter' %}
</form>
{% endif %}

{% render_table table %}

{% endblock %}

djenealog/templates/djenealog/individu_form.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/form.html' %}

{% if individu.pk %}

<dl class="row">
  <dt class="col-sm-3">Graphe</dt>
  <dd class="col-sm-9">
    <a href="{% url 'djenealog:graph' %}?individu={{ individu.pk }}&upper=1&lower=1">famille</a> -
    <a href="{% url 'djenealog:graph' %}?individu={{ individu.pk }}&upper=1&lower=1&extended=1">famille étendue</a>
  </dd>

  <dt class="col-sm-3">Annivs</dt>
  <dd class="col-sm-9">
    <a href="{% url 'djenealog:annivs' %}?individu={{ individu.pk }}&upper=1&lower=1">famille</a> -
    <a href="{% url 'djenealog:annivs' %}?individu={{ individu.pk }}&upper=1&lower=1&extended=1">famille étendue</a>
  </dd>

  <dt class="col-sm-3">Naissance</dt>
  <dd class="col-sm-9">
  {% if individu.naissance %}
  {{ individu.naissance }}
  <a href="{% url 'djenealog:naissance' pk=individu.naissance.pk %}">edit</a>
  <a href="{% url 'djenealog:del-naissance' pk=individu.naissance.pk %}">delete</a>
  {% else %}
  <a href="{% url 'djenealog:add-naissance' pk=individu.pk %}">Ajouter une naissance</a>
  {% endif %}
  </dd>

  <dt class="col-sm-3">Décès</dt>
  <dd class="col-sm-9">
  {% if individu.deces %}
  {{ individu.deces }}
  <a href="{% url 'djenealog:deces' pk=individu.deces.pk %}">edit</a>
  <a href="{% url 'djenealog:del-deces' pk=individu.deces.pk %}">delete</a>
  {% else %}
  <a href="{% url 'djenealog:add-deces' pk=individu.pk %}">Ajouter un décès</a>
  {% endif %}
  </dd>

  {% if individu.parents %}
  <dt class="col-sm-3">Parents</dt>
  <dd class="col-sm-9">
  {{ individu.parents.get_link }}
  </dd>
  {% endif %}

  {% if individu.mari.exists or individu.femme.exists %}
  <dt class="col-sm-3">Couples</dt>
  <dd class="col-sm-9">
    {% for couple in individu.mari.all %}
    {{ couple.get_link }}
    {% endfor %}
    {% for couple in individu.femme.all %}
    {{ couple.get_link }}
    {% endfor %}
  </dd>
  {% endif %}

  <dt class="col-sm-3">Supprimer</dt>
  <dd class="col-sm-9"><a href="{% url 'djenealog:del-individu' pk=individu.pk %}">delete</a></dd>
</dl>
{% endif %}

{% endblock %}

{% block style %}
{{ form.media.css }}
{% endblock %}

{% block scripts %}
{{ form.media.js }}
{% endblock %}

djenealog/templates/djenealog/lieu_list.html
{% extends 'base.html' %}
{% load leaflet_tags l10n %}

{% block style %}
{% leaflet_css %}
<style>
    .leaflet-container {  /* all maps */
        width:  100%;
        height: 800px;
    }
</style>
{% endblock %}

{% block content %}
{% leaflet_map "main" callback="main_map_init" %}
{% endblock %}

{% block scripts %}
{% leaflet_js %}
<script type="text/javascript">
  function main_map_init (map, options) {
    {% for object in object_list %}
    L.marker([{{ object.point.1|unlocalize }}, {{ object.point.0|unlocalize }}]).addTo(map)
      .bindPopup('<a href="{{ object.wd_url }}">{{ object }}</a>');
    {% endfor %}
  }
</script>
{% endblock %}

djenealog/templates/djenealog/stats.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-sm-6">
    <h3 class="text-center">Statistiques</h3>
    <dl class="row">
      <dt class="col-sm-6">Individus</dt><dd class="col-sm-6">{{ individus }}</dd>
      <dt class="col-sm-6">Hommes</dt><dd class="col-sm-6">{{ hommes }}</dd>
      <dt class="col-sm-6">Femmes</dt><dd class="col-sm-6">{{ femmes }}</dd>
      <dt class="col-sm-6">Couples</dt><dd class="col-sm-6">{{ couples }}</dd>
      <dt class="col-sm-6">Naissances</dt><dd class="col-sm-6">{{ naissances }}</dd>
      <dt class="col-sm-6">Déces</dt><dd class="col-sm-6">{{ deces }}</dd>
      <dt class="col-sm-6">Mariages</dt><dd class="col-sm-6">{{ mariages }}</dd>
      <dt class="col-sm-6">Pacs</dt><dd class="col-sm-6">{{ pacs }}</dd>
      <dt class="col-sm-6">Divorces</dt><dd class="col-sm-6">{{ divorces }}</dd>
    </dl>
  </div>
  <div class="col-sm-6">
    <h3 class="text-center">Détection d’erreurs potentielles</h3>
    <dl class="row">
      <dt class="col-sm-6">Centenaires vivants</dt><dd class="col-sm-6">{{ centenaires }}</dd>
      <dt class="col-sm-6">Maris pas masculins</dt><dd class="col-sm-6">{{ maris_pas_masculins }}</dd>
      <dt class="col-sm-6">Femmes pas feminines</dt><dd class="col-sm-6">{{ femmes_pas_feminines }}</dd>
      <dt class="col-sm-6">Divorces sans mariages</dt><dd class="col-sm-6">{{ divorces_sans_mariages }}</dd>
      <dt class="col-sm-6">Assexués</dt><dd class="col-sm-6">{{ assexues }}</dd>
    </dl>
  </div>
</div>

{% if request.user.is_authenticated %}
<table class="table">
  <tr><th>Nom</th><th>Naissance</th><th>Épouse</th><th>Total</th></tr>
  {% for sum, noms, epouses, nom in noms %}
  <tr>
    <td>{{ nom }}</td>
    <td><a href="{% url 'djenealog:individus' %}?nom={{ nom }}">{{ noms }}</a></td>
    <td><a href="{% url 'djenealog:individus' %}?epouse={{ nom }}">{{ epouses }}</a></td>
    <td>{{ sum }}</td>
  </tr>
  {% endfor %}
  <tr><th>Prénom</th><th>Naissance</th><th>Usage</th><th>Total</th></tr>
  {% for sum, prenoms, usages, prenom in prenoms %}
  <tr>
    <td>{{ prenom }}</td>
    <td><a href="{% url 'djenealog:individus' %}?prenom={{ prenom }}">{{ prenoms }}</a></td>
    <td><a href="{% url 'djenealog:individus' %}?usage={{ prenom }}">{{ usages }}</a></td>
    <td>{{ sum }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}

{% endblock %}

djenealog/templates/djenealog/tables.html
{% extends 'django_tables2/bootstrap.html' %}
{% load django_bootstrap5 %}

{% block pagination %}
{% bootstrap_pagination table.page extra=request.GET.urlencode %}
{% endblock %}